### ISSUE TITLE
Revoke Operation Deadlock

### ISSUE THREAD

**Issue by gypsephi** [ManyThreads/mythos#154]
By mistake, I found a locking issue in  void RevokeOperation::_delete(Tasklet* t, result_t* res, CapEntry& entry, IKernelObject* guarded).
aquire() aquires a lock which is only freed in _startAsyncDelete and _deleteObject (by using release()).
RevokeOperation::response() calls _deleteObject, but in the following code the response method of "res" is called which is a different implementation.
entry.kill() fails in case of an already freed cap and then leaves the class locked.

Code:
```
if (!acquire()) { /// @todo should never fail because of the outer monitored request! ?
      res->response(t, Error::LOST_RACE);
      monitor.requestDone();
      return;
    }
    if (!entry.kill()) {
      MLOG_DETAIL(mlog::cap, "Can not kill entry", &entry, entry);
      res->response(t, Error::LOST_RACE);
      monitor.requestDone();
      return;
    }
    _result = _delete(&entry, entry.cap()).state();
    _startAsyncDelete(t);
```

**Comment by kubanrob** [comment]
The lock is used to protect the Portal from being deleted when it-self runs a RevokeOperation. Similarly, the lock cancels the start of the RevokeOperation process if the Portal is going to be deleted.
So the todo is not accurate as Portal and RevokeOperation don't share a monitor. We do need that lock.

You're right, both of the entry functions `_delete` and `_revoke` should surrender the lock if they fail.
