### ISSUE TITLE
port fixes from feature branches

### ISSUE THREAD

**Issue by kubanrob** [ManyThreads/mythos#170]
There are some bug fixes in long-term feature branches (e.g.  in [i164_processor_management](https://github.com/ManyThreads/mythos/tree/i164_processor_management)) that are already useful for everybody. These should be ported to master occasionally.

- [x] `IOPort16` warnings
- [x] unaligned mmap in userspace

**Feel free to update/reopen this issue if some new bug fixes are available in a feature branch.**

**Comment by gypsephi** [comment]
mmap was already aligned in master: https://github.com/ManyThreads/mythos/blob/59e6baa9cd78eb21cc0db9b990037991ca7222be/kernel/runtime/cxx/runtime/cxxsupport.cc#L223

**Comment by gypsephi** [comment]
fixed warning in PhysPtr
